# Generated by Django 2.1.7 on 2019-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='shop',
            name='poster',
            field=models.CharField(max_length=600),
        ),
    ]
